/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Database;

/**
 *
 * @author Jim
 */
public class ErrorCodePanel extends javax.swing.JPanel
{

    private Database db = null;
    private ErrorCodeOptionsPanel optionsPanel = null;

    /**
     * Creates new form UserPanel
     *
     * @param db
     */
    public ErrorCodePanel(Database db)
    {
        initComponents();
        this.db = db;
        db.getErrorCodes();
        fillList();
    }
    
    
    public void fillList(){
        errorCodeList.setListData(db.toErrorCodeArray());
    }
    

    public void setDatabase(Database db)
    {
        this.db = db;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        addErorCodeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        errorCodeList = new javax.swing.JList<String>();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 500));

        addErorCodeButton.setText("add");
        addErorCodeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addErorCodeButtonActionPerformed(evt);
            }
        });

        errorCodeList.setPreferredSize(null);
        errorCodeList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                errorCodeListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(errorCodeList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addGap(424, 424, 424))
            .addGroup(layout.createSequentialGroup()
                .addGap(574, 574, 574)
                .addComponent(addErorCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addErorCodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addErorCodeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addErorCodeButtonActionPerformed
    {//GEN-HEADEREND:event_addErorCodeButtonActionPerformed
        NewErrorCodePanel newErrorPanel = new NewErrorCodePanel(db);
        int result = JOptionPane.showConfirmDialog(this, newErrorPanel, "Add new errorcode", JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION) db.addErrorCode(newErrorPanel.getFiLanguage(), newErrorPanel.getDescriptionTextField().getText());
        errorCodeList.setListData(db.toErrorCodeArray());
    }//GEN-LAST:event_addErorCodeButtonActionPerformed

    private void errorCodeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_errorCodeListValueChanged
        try{
            optionsPanel = new ErrorCodeOptionsPanel(db, db.alErrorCodes.get(errorCodeList.getSelectedIndex()).id, errorCodeList);
            JOptionPane.showMessageDialog(this, optionsPanel, "Errorcode", JOptionPane.DEFAULT_OPTION);
        }
        catch(IndexOutOfBoundsException e){
            
        }
    }//GEN-LAST:event_errorCodeListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addErorCodeButton;
    private javax.swing.JList<String> errorCodeList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
