/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JList;
import model.Database;
import model.Language;

/**
 *
 * @author jim
 */
public class ErrorCodeOptionsPanel extends javax.swing.JPanel {

    private Database db = null;
    private int id;
    private JList errorCodeList = null;
    /**
     * Creates new form LanguageOptionsPanel
     */
    public ErrorCodeOptionsPanel(Database db, int id, JList errorCodeList) {
        initComponents();
        fillComboBox(db);
        this.db = db;
        this.id = id;
        this.errorCodeList = errorCodeList;
        updateDescription();
        
    }
    
    public void updateDescription(){
        if(errorCodeList != null){
            try{
                Language language = (Language)languageComboBox.getSelectedItem();
                String sampleDescription = errorCodeList.getSelectedValue().toString();
                descriptionTextField.setText(db.getErrorCodeDescription(id, language));
            }
            catch(NullPointerException e){
                
            }
        }
    }
    
    public void fillComboBox(Database db){
        ArrayList<Language> alLanguages = db.alLanguages;
        for (Language alLanguage : alLanguages)
        {
            languageComboBox.addItem(alLanguage);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        languageComboBox = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        deleteAllButton = new javax.swing.JButton();

        jLabel2.setText("description:");

        descriptionTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                descriptionTextFieldKeyReleased(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("language:");

        languageComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                languageComboBoxItemStateChanged(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addButtonActionPerformed(evt);
            }
        });

        deleteAllButton.setText("Delete all");
        deleteAllButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(languageComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton)
                        .addGap(8, 8, 8)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(languageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteAllButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        db.updateErrorCodeDescription(id, (Language)languageComboBox.getSelectedItem(), descriptionTextField.getText());
        updateDescription();
        errorCodeList.setListData(db.toErrorCodeArray());
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        db.deleteErrorCodeDescription(id, ((Language)languageComboBox.getSelectedItem()).id);
        updateDescription();
        errorCodeList.setListData(db.toErrorCodeArray());
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void languageComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_languageComboBoxItemStateChanged
    {//GEN-HEADEREND:event_languageComboBoxItemStateChanged
        updateDescription();
        if(descriptionTextField.getText().isEmpty()) {
            addButton.setEnabled(false);
        }
    }//GEN-LAST:event_languageComboBoxItemStateChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addButtonActionPerformed
    {//GEN-HEADEREND:event_addButtonActionPerformed
        String description = descriptionTextField.getText();
        Language language = (Language)languageComboBox.getSelectedItem();
        
        db.addErrorCodeDescription(language, id, description);
        updateDescription();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteAllButtonActionPerformed
    {//GEN-HEADEREND:event_deleteAllButtonActionPerformed
        db.deleteAllErrorCodeDescriptions(id);
        updateDescription();
        errorCodeList.setListData(db.toErrorCodeArray());
    }//GEN-LAST:event_deleteAllButtonActionPerformed

    private void descriptionTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_descriptionTextFieldKeyReleased
    {//GEN-HEADEREND:event_descriptionTextFieldKeyReleased
        if(descriptionTextField.getText().isEmpty())addButton.setEnabled(false);
        else addButton.setEnabled(true);
    }//GEN-LAST:event_descriptionTextFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox languageComboBox;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
