/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.Database;

/**
 *
 * @author jim
 */
public class FilePanel extends javax.swing.JPanel {
    
    
    private Database db = null;
    private FileOptionsPanel optionsPanel = null;
    /**
     * Creates new form UserPanel
     */
    public FilePanel(Database db) {
        initComponents();
        this.db = db;
        db.getTextFiles();
        fillList();
    }
    
    public void fillList(){
        
        fileList.setListData(db.toTextFileArray());
    }
    public void setDatabase(Database db)
    {
        this.db = db;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFileButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileList = new javax.swing.JList<>();

        setBackground(new java.awt.Color(204, 255, 255));

        addFileButton.setText("add");
        addFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileButtonActionPerformed(evt);
            }
        });

        fileList.setPreferredSize(null);
        fileList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fileListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(fileList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(414, 414, 414))
            .addGroup(layout.createSequentialGroup()
                .addGap(598, 598, 598)
                .addComponent(addFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addFileButtonActionPerformed
    {//GEN-HEADEREND:event_addFileButtonActionPerformed
        NewFilePanel filePanel = new NewFilePanel();
        int result = JOptionPane.showConfirmDialog(this, filePanel, "Add new filepath", JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION)
        {
            db.addTextFile(filePanel.getPath());
        }
        fileList.setListData(db.toTextFileArray());
    }//GEN-LAST:event_addFileButtonActionPerformed

    private void fileListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_fileListValueChanged
    {//GEN-HEADEREND:event_fileListValueChanged
        optionsPanel = new FileOptionsPanel(db, db.alTextFiles.get(fileList.getSelectedIndex()), fileList);
        JOptionPane.showMessageDialog(this, optionsPanel, "Textfile", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_fileListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFileButton;
    private javax.swing.JList<String> fileList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
