/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.Database;

/**
 *
 * @author jim
 */
public class SmsPanel extends javax.swing.JPanel {
    
    
    private Database db = null;
    private SmsOptionsPanel optionsPanel = null;
    /**
     * Creates new form UserPanel
     */
    public SmsPanel(Database db) {
        initComponents();
        this.db = db;
        db.getSmses();
        fillList();
    }
    
    public void fillList(){
        smsList.setListData(db.toSmsArray());
    }
    public void setDatabase(Database db)
    {
        this.db = db;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        addSmsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        smsList = new javax.swing.JList<String>();

        setBackground(new java.awt.Color(204, 255, 255));

        addSmsButton.setText("add");
        addSmsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addSmsButtonActionPerformed(evt);
            }
        });

        smsList.setPreferredSize(null);
        smsList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                smsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(smsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(414, 414, 414))
            .addGroup(layout.createSequentialGroup()
                .addGap(598, 598, 598)
                .addComponent(addSmsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSmsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addSmsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addSmsButtonActionPerformed
    {//GEN-HEADEREND:event_addSmsButtonActionPerformed
        NewSmsPanel smsPanel = new NewSmsPanel();
        int result = JOptionPane.showConfirmDialog(this, smsPanel, "Add new sms", JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION)
        {
            db.addSms(smsPanel.getNumber(), smsPanel.getName());
        }
        smsList.setListData(db.toSmsArray());
    }//GEN-LAST:event_addSmsButtonActionPerformed

    private void smsListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_smsListValueChanged
    {//GEN-HEADEREND:event_smsListValueChanged
        optionsPanel = new SmsOptionsPanel(db, db.alSms.get(smsList.getSelectedIndex()), smsList);
        JOptionPane.showMessageDialog(this, optionsPanel, "Sms", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_smsListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSmsButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> smsList;
    // End of variables declaration//GEN-END:variables
}
