/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.Database;

/**
 *
 * @author jim
 */
public class UserPanel extends javax.swing.JPanel {
    
    
    private Database db = null;
    private UserOptionsPanel optionsPanel = null;
    /**
     * Creates new form UserPanel
     */
    public UserPanel(Database db) {
        initComponents();
        this.db = db;
        db.getUsers();
        fillList();
    }
    
    public void fillList(){
        userList.setListData(db.toUserArray());
    }
    public void setDatabase(Database db)
    {
        this.db = db;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUserButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();

        setBackground(new java.awt.Color(204, 255, 255));

        addUserButton.setText("add");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        userList.setPreferredSize(null);
        userList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                userListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(userList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(414, 414, 414))
            .addGroup(layout.createSequentialGroup()
                .addGap(598, 598, 598)
                .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addUserButtonActionPerformed
    {//GEN-HEADEREND:event_addUserButtonActionPerformed
        NewUserPanel userPanel = new NewUserPanel();
        int result = JOptionPane.showConfirmDialog(this, userPanel, "Add new user", JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION)
        {
            db.addUser(userPanel.getName(), userPanel.getPassword(), userPanel.getLevel());
        }
        userList.setListData(db.toUserArray());
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void userListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_userListValueChanged
    {//GEN-HEADEREND:event_userListValueChanged
        optionsPanel = new UserOptionsPanel(db, db.alUsers.get(userList.getSelectedIndex()), userList);
        JOptionPane.showMessageDialog(this, optionsPanel, "User", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_userListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
